# Generated by Django 5.0.2 on 2024-03-10 13:08

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=100)),
                ('email', models.EmailField(help_text='Enter your email address', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your phone number', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='Phone number must start with +98 and have 10 digits.', regex='^\\+98\\d{10}$')])),
                ('message', models.TextField(help_text='Enter your message')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
